-- ==============================================================================
-- DDL ORACLE: GESTÃO DE OBRAS
-- ==============================================================================

CREATE TABLE EMPRESA (
    ID_EMPRESA NUMBER(10) NOT NULL,
    CNPJ VARCHAR2(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR2(100) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    CONSTRAINT PK_EMPRESA PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT UQ_EMP_CNPJ UNIQUE (CNPJ)
);

CREATE TABLE OBRA (
    ID_OBRA NUMBER(10) NOT NULL,
    ID_EMPRESA NUMBER(10) NOT NULL,
    NOME_OBRA VARCHAR2(150) NOT NULL,
    ORCAMENTO_TOTAL NUMBER(15,2),
    STATUS VARCHAR2(20) DEFAULT 'EM_PLANEJAMENTO',
    CONSTRAINT PK_OBRA PRIMARY KEY (ID_OBRA),
    CONSTRAINT FK_OBRA_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA)
);

CREATE TABLE MEDICAO_FISICA (
    ID_MEDICAO NUMBER(10) NOT NULL,
    ID_OBRA NUMBER(10) NOT NULL,
    ANO_REFERENCIA NUMBER(4) NOT NULL,
    MES_REFERENCIA NUMBER(2) NOT NULL,
    VALOR_EXECUTADO NUMBER(15,2) NOT NULL,
    DATA_APROVACAO DATE,
    CONSTRAINT PK_MEDICAO PRIMARY KEY (ID_MEDICAO),
    CONSTRAINT FK_MEDICAO_OBRA FOREIGN KEY (ID_OBRA) REFERENCES OBRA(ID_OBRA)
);

-- Índices (Testando o peso "idx" do SRE e a identificação de hotspots temporais)
CREATE INDEX IDX_MEDICAO_TEMPO ON MEDICAO_FISICA (ANO_REFERENCIA, MES_REFERENCIA);
CREATE INDEX IDX_OBRA_STATUS ON OBRA (STATUS);

-- Comentários (Testando o motor de extração de documentação)
COMMENT ON TABLE EMPRESA IS 'Tabela core de cadastro das empreiteiras parceiras.';
COMMENT ON COLUMN EMPRESA.CNPJ IS 'CNPJ da empresa sem máscara de formatação.';
COMMENT ON TABLE OBRA IS 'Projetos de engenharia e obras públicas cadastradas.';
COMMENT ON COLUMN MEDICAO_FISICA.ANO_REFERENCIA IS 'Ano da medição para fins de faturamento e auditoria temporal.';